import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import MasterPage from './components/MasterPage';
import { AuthContextProvider } from "./lib/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <MasterPage>
            {children}
          </MasterPage>
        </AuthContextProvider>
      </body>
    </html>
  );
}
